# Generated by Django 5.0.3 on 2024-04-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_system', '0004_menuitem_description_menuitem_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='minimum_quantity',
            field=models.IntegerField(default=10),
        ),
    ]
