# Generated by Django 5.0.3 on 2024-04-20 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_system', '0006_alter_employee_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerorder',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
