# Generated by Django 5.0.3 on 2024-04-22 16:53

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_system', '0007_remove_customerorder_customer_delete_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+10000000000', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
